language: java
# Needed for ping to work in the test cases.
sudo: true
jdk:
  - oraclejdk8
os:
  - linux
# Handle git submodules on our own.
git:
  submodules: false
# Replacing the SSH URL with the public URL and then updating the submodule.
before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive
script:
  - gradle clean build publish
  - bash <(curl -s https://codecov.io/bash)
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
